server:
  port: 8080
spring:
  application:
    name: demo
  profiles:
#    active: @spring.profiles.active@
    active: dev
# Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health: # config for EKS
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  prometheus:
    metrics:
      export:
        step: 5s
        enabled: true

# Logging
#logging:
#  level:
#    root: INFO
#    web: OFF
#    org.springframework: INFO
#    org.apache: OFF
#    kafka: OFF